### ISSUE TITLE
MSA alignment gets misaligned when zooming in

### ISSUE THREAD

**Issue by gustavo-salazar** [ebi-webcomponents/nightingale#108]
**Describe the bug**
If you zoom in, deep enough into an alignment the bases get misaligned. Which is mostly noticeable in the beginning of the alignment.

**To Reproduce**
1. Go to  https://ebi-webcomponents.github.io/nightingale/#/msa
2. Zooming into the first residues in the example, sai between residues 1 to 10.
3. Notice gap between the position label and the first green block.

**Expected behavior**
No gap in step 3

**Screenshots**
<img width="242" alt="Screenshot 2020-09-17 at 10 25 12" src="https://user-images.githubusercontent.com/46671268/93452229-15bfd180-f8d0-11ea-91ed-d07916cb92ef.png">

**Additional context**
@dlrice I haven't investigate properly, but just wondering if this is related with the start/end labels, or do you think is a problem in the alignments library itself.

**Comment by dlrice** [comment]
Good catch @gustavo-salazar - yeah it's the start/end labels for sure as the problem disappears if I uncheck the `show left coordinates` checkbox in the demo page. Will have to look into this a bit more to see where the fix needs to be applied (here or the react-msa-viewer).

**Comment by gustavo-salazar** [comment]
Ha... I didn't notice that, I was just playing with the offset option, but didn't disable the show label checkbox. At least that gives us a clue of where to start looking. 

Have a look and let me know if you want me to help with it

**Comment by gustavo-salazar** [comment]
There is also something funny with the right coordinate label.
look when I zoom to see only the first 4 residues:
<img width="695" alt="Screenshot 2020-09-18 at 11 47 13" src="https://user-images.githubusercontent.com/46671268/93589477-c26b8300-f9a4-11ea-8b49-9c0409ad7e5b.png">
* the label says 3 when I think it should says 4, or am I missing something on what are this labels meant.
* There is a gap between the end of residue 4 and the space represented in the navigation bar.

This last point becomes more obvious when the label is hidden:
<img width="697" alt="Screenshot 2020-09-18 at 11 52 42" src="https://user-images.githubusercontent.com/46671268/93589915-8127a300-f9a5-11ea-94ae-a22657ce684a.png">
As part of the residue 5 is shown. 

This is quite an issue when trying to use `protvista-msa` with other tracks, because then it doesn't align properly, and the error although less noticeable is more substantial when zooming out

**Comment by dlrice** [comment]
I think https://github.com/ebi-webcomponents/react-msa-viewer/tree/alignment-and-end-coord-bug-fix fixes the growing coordinate label but the coordinate needs some more attention. Seems like there is some rounding issues arising.

**Comment by dlrice** [comment]
Also noticed an issue when zoomed in quite a bit and scrolling vertically where the label and coordinate are no longer adjacent but have some y-offset discrepancy.
<img width="286" alt="Screenshot 2020-09-18 at 18 40 02" src="https://user-images.githubusercontent.com/4357962/93628380-5efe4700-f9de-11ea-93d8-b722ae57941f.png">
This bug is also originates in react-msa-viewer.

**Comment by gustavo-salazar** [comment]
Hey @dlrice, I merge the suggested branch on the one I'm working and seems to have solve the initial gap issue. Thanks.

And now I'm busy checking an error of alignment when using msa with other tracks.
I think it is related with the margin that msa inherits from track. We are not using it, and I think that's causing a miscalculation of the width per base in the MSA.
