### ISSUE TITLE
Improve data-adapter-* loading strategy

### ISSUE THREAD

**Issue by xwatkins** [ebi-webcomponents/nightingale#15]
Currently `data-adapters` allow a bottom up approach for loading data, processing the data so it can be displayed by a protvista visualisation component:
```
<protvista-track>
   <protvista-feature-adapter>
      <data-loader>...</data-loader>
   </protvista-feature-adapter>
</protvista-track>
```
As for different tracks the data can be loaded from the same locations, this means that this processing happens multiple times when it could happen only once (the data however is cached by the `data-loader` downstream of the `data-adapter-*`).

One suggestion would be to not have `data-adapters` as children of tracks, but have them alongside and for the data to be passed through `protvista-manager`. This would mean that tracks would somehow have to register to a `data-adapter`:
```
<protvista-feature-adapter id="main-adapter">
   <data-loader>...</data-loader>
</protvista-feature-adapter>
<protvista-track data-provider="main-adapter"/ >
```
Another suggestion would be to use `data-adapters` as utilities so the client could call functions to process the data before passing it to the tracks as a property. These functions could be exported by the module so the client wouldn't have to use it as a web component if they don't want to.

**Comment by sacdallago** [comment]
Just clashing against this right now, I'd also suggest not to have them as children.

**Comment by xwatkins** [comment]
We've actually started work on this - the data loaders now all export a `{transformData}` function. Maybe that helps?
