### ISSUE TITLE
Incorrect mouse offset when hovering mouse over nightingale-linegraph-track

### ISSUE THREAD

**Issue by somnambulism** [ebi-webcomponents/nightingale#151]
**Describe the bug**
For nightingale-linegraph-track, when you point the mouse on the graph, the circle appears when the pointer is to the left of the line.

**To Reproduce**
1. Go to https://ebi-webcomponents.github.io/nightingale/#/graph1
2. Scroll down the page to see the component demo
3. Point the mouse slightly to the left of the graph
4. See the circle and the text appears to the left, not on the line
(The same issue is observed with any application of the component, not only on the demo)

**Expected behavior**
The circle appears when the mouse is pointed exactly on the line. The text shows the correct value.

**Screenshots**
![image](https://user-images.githubusercontent.com/3225036/118967367-4aaa8980-b973-11eb-9842-a527ff192146.png)
Mouse is pointed to the left of the graph, circles and text appear in the blank space.
![image](https://user-images.githubusercontent.com/3225036/118969490-c9a0c180-b975-11eb-8c59-8a6d926616a3.png)
Mouse is pointed on the left end of the graph, text shows '40' and '10'. Should be '20' and '0' in this position.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome, Edge

**Comment by gustavo-salazar** [comment]
Hey there,
Really sorry we never replied to your reported issue. We are working on a complete rewrite of all the components and hope to have a beta release by November. I'll keep this issue open as a reference to the problem, so it doesn't propagate to the new version. However, it won't be fixed in the current codebase
