### ISSUE TITLE
protvista structure error on localhost

### ISSUE THREAD

**Issue by rizwan-ishtiaq** [ebi-webcomponents/nightingale#171]
**Describe the bug**
There are multiple errors while working on localhost. There error are quite random even i am not sure to explain how to reproduce them. Normally i have seen them when swtiching between models with out letting previous model load completly.

**To Reproduce**
1. Load alphfold structure using protvista-structure
2. Then load PDB structure
3. See error

**Expected behavior**
There should not be any errors.

**Screenshots**
![Screenshot from 2021-09-14 11-31-55](https://user-images.githubusercontent.com/34174422/138884861-06d60c64-e988-475f-96f7-817ad8e590cc.png)
![Screenshot from 2021-09-14 11-32-22](https://user-images.githubusercontent.com/34174422/138884906-c9617cb2-8747-4557-96d5-1697ef7b1eee.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Browser Chrome
 - Version 94.0.4606.81 (Official Build) (64-bit)

**Additional context**
protvista-structure@3.4.0

**Comment by gustavo-salazar** [comment]
Hey as mentioned in the other issue, we are migrating the components into a newer code base: Lit elements with typescript.

**Comment by gustavo-salazar** [comment]
Hey the new version of the protvista component won't use the React embedded in mol* so this error won't apply to it. 
closing it now
