### ISSUE TITLE
Feature request: can selection mode be exposed on Protvista-Structure?

### ISSUE THREAD

**Issue by radusuciu** [ebi-webcomponents/nightingale#187]
I would like to make use of selection mode in this component. In Mol* you can toggle this mode by clicking on this button:

![image](https://user-images.githubusercontent.com/1108600/153305809-ebf9be1f-de02-487a-af0b-e7c1c0f76aff.png)

However, this is lacking in this component as it is turned off by default here:

https://github.com/ebi-webcomponents/nightingale/blob/34eb2f567ef6a35f705fbad08d32839ad796ed30/packages/protvista-structure/src/structure-viewer.ts#L43

Can this be added as a property we can toggle on the component? More broadly it might make sense to make all of `viewerOptions` configurable for maximum flexibility -- of course keeping the existing settings as defaults.

Thanks!

**Comment by radusuciu** [comment]
Would you accept a PR for this?

**Comment by xwatkins** [comment]
Yes, definitely.
