### ISSUE TITLE
Enable customizing structure download URLs

### ISSUE THREAD

**Issue by prihoda** [ebi-webcomponents/nightingale#193]
**Is your feature request related to a problem? Please describe.**
We want to use protvista-structure to display internally curated structures. For that reason, we need to customize the download URLs.

**Describe the solution you'd like**
I would like to customize the mapping and download URLs using attributes of `protvista-structure` component.

**Describe alternatives you've considered**
Not sure about any other alternatives since URLs are currently hardcoded.

**Additional context**

See PR https://github.com/ebi-webcomponents/nightingale/pull/192

**Comment by prihoda** [comment]
Hi @gustavo-salazar I noticed that although the PR was merged and released in `3.6.0`, the `dist` folder in the NPM package still contains the old code.

Please see:
https://registry.npmjs.org/protvista-structure/-/protvista-structure-3.6.0.tgz

In `src/protvista-structure.ts` you can see the customizable URLs (private _uniProtMappingUrl = ...)

But in `dist/protvista-structure.js` and `dist/es/protvista-structure.js` you get the hardcoded URL.

**Comment by gustavo-salazar** [comment]
Hey @prihoda 
Sorry, I got bitten by lerna again... published without building... so sorry. I have re-published it as `3.6.1` https://www.npmjs.com/package/protvista-structure

Please have a look if I got it right this time.

Cheers,
Gustavo.

**Comment by prihoda** [comment]
Works great, thanks!
