### ISSUE TITLE
Add citation information in README

### ISSUE THREAD

**Issue by LLautenbacher** [ebi-webcomponents/nightingale#201]
Currently, there is no paper specified in the README for people to cite if they are mentioning nightingale in a paper.
Is there a paper published for nightingale, or do you want people to cite the older ProtVista paper (https://doi.org/10.1093/bioinformatics/btx120)?

**Comment by gustavo-salazar** [comment]
Hello there, so sorry for the delay.
TBH, we haven't put time into writing an up-to-date paper. So we will be happy if you include the GitHub repo in your publication for now. We are working on a new version of the library, aiming to have a version to show in November. And once that's done I think we will have content and time to put into a Nightingale publication. 🤞🏽

**Comment by gustavo-salazar** [comment]
A long time after this but we finally have a publication and I just added to the readme.

https://doi.org/10.1093/bioadv/vbad064
