### ISSUE TITLE
Add support for structure highlight across gaps in mapping

### ISSUE THREAD

**Issue by prihoda** [ebi-webcomponents/nightingale#206]
Problem 1: Highlighting a structure region is currently not supported across alignment gaps in the sequence-structure mapping.

For example, this PDB contains an insertion at position 41, so the mapping contains two items, one from uniprot position 1-40, the second from uniprot position 41-164: https://www.ebi.ac.uk/pdbe/api/mappings/uniprot/102L

When trying to highlight range 37-42, the current position mapping fails, because the start and end coordinates are not found in the same mapping item:

https://github.com/ebi-webcomponents/nightingale/blob/91baedb57d58d40d784fcf7acd7e65c14bbcde52/packages/protvista-structure/src/position-mapping.ts#L63-L73

Problem 2: When multiple chains are present, highlight is applied to all chains, even though it should only be applied to specific chains present in the mapping.

The molstar condition only checks the residue number, not the chain:

https://github.com/ebi-webcomponents/nightingale/blob/91baedb57d58d40d784fcf7acd7e65c14bbcde52/packages/protvista-structure/src/structure-viewer.ts#L199-L206

You can try this out by selecting structure `1BRC` from the table at https://ebi-webcomponents.github.io/nightingale/#/structure and clicking at residues in the smaller chain. Residues in the larger chain will also be highlighted.

**Comment by gustavo-salazar** [comment]
@prihoda I'm guessing #207 solves this issue. Thanks for the contribution.
I'm closing this ticket, but feel free to reopen it if there is anything missing.
