### ISSUE TITLE
Protvista-filter not working properly

### ISSUE THREAD

**Issue by mandarsd** [ebi-webcomponents/nightingale#24]
variant plot filtering is inconsistent.
protvista-uniport example accession - P05067
In this example I could see 'Uncertain' category data in the plot but nothing appears on applying the filter for this category

![image](https://user-images.githubusercontent.com/12937838/56739535-c91da880-6766-11e9-8753-8527de7012f6.png)

**Comment by mandarsd** [comment]
One more thing, the variation-graph is also not consistent when filters are applied

**Comment by xwatkins** [comment]
Should be fixed - please make another issue for `variation-graph` if issue is still there for it
