### ISSUE TITLE
Navigation slider disappear when clicking outside region.

### ISSUE THREAD

**Issue by ylin2139** [ebi-webcomponents/nightingale#246]
When clicking the outside region of the slider in navigation components, the slider disappears. This can be seen here: https://ebi-webcomponents.github.io/nightingale/?path=/story/components-manager--all-tracks.

**Comment by gustavo-salazar** [comment]
Issue solved and version `4.0.0` deployed 🎉

**Comment by ylin2139** [comment]
Hi Gustavo,

Thank you for resolving this issue. I incorporated the change into my application.

One feature request I have now is to have the tooltip function in the track component. When mousing over a feature in track, a tooltip can display the accession or customized content. It is a very commonly used feature. I hacked the track component by applying the tippy.js tippy function in rendering. It works well until I use my hacked component in my react application utilizing tailwindcss, I suspect the CSS has to be handled specifically. I will figure it out. However, it would be nice if it could come with the track component directly.

Thanks again for your nice work.

Yuan

From: Gustavo A. Salazar ***@***.***>
Date: Wednesday, March 22, 2023 at 10:54 AM
To: ebi-webcomponents/nightingale ***@***.***>
Cc: Lin, Yuan ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [ebi-webcomponents/nightingale] Navigation slider disappear when clicking outside region. (Issue #246)

Issue solved and version 4.0.0 deployed 🎉

**Comment by odysseyjake** [comment]
I realize this issue is closed but I would add my +1 for directly implementing tooltips for track features, or at least posting a worked example of using a 3rd party tooltip manager to display tool tips. The inclusion of `tooltipContents` in the `Features` data model makes it seem like tooltips should be supported.
