### ISSUE TITLE
Documentation is not sufficient to replicate examples

### ISSUE THREAD

**Issue by DanBuchan** [ebi-webcomponents/nightingale#261]
Documentation is generally very poor outside the use case of nightingale-sequence and the "getting started" examples at `ebi-webcomponents.github.io`. 

For instance, `https://ebi-webcomponents.github.io/nightingale/?path=/story/components-tracks-alignments-readme--page` does not explain how to pass an MSA to the component, nor does it explain what format this data should be in.

**Comment by gustavo-salazar** [comment]
Thanks for reporting it.
As you can see from #249 the documentation is still a work in progress, but unfortunately, the time we can dedicate to the project is limited. I hope to be able to get to it soon. PRs are also very welcome!

In the meantime, you can see the structure of the data in the storybook example: https://github.com/ebi-webcomponents/nightingale/blob/main/stories/10.MSA/NightingaleMSA.stories.ts

**Comment by DanBuchan** [comment]
No worries. Looking forward to the docs being more complete.
