### ISSUE TITLE
Shape does not work  in protvista track

### ISSUE THREAD

**Issue by RupaliMahadik** [ebi-webcomponents/nightingale#28]
https://github.com/ebi-webcomponents/nightingale/tree/master/packages/protvista-track

{
    accession: String,
    start: Number,
    end: Number,
    color?: String,
    shape?: rectangle|bridge|diamnond|chevron|catFace|triangle|wave|hexagon|pentagon|circle|arrow|doubleBar,
    tooltipContent?: String
}

shape?: rectangle|bridge|diamnond|chevron|catFace|triangle|wave|hexagon|pentagon|circle|arrow|doubleBar,
 many shapes does not work for example: diamnond and hexagon

**Comment by xwatkins** [comment]
There was a typo in `diamond` in the doc. `hexagon` seems to work ok, please close if issue is resolved.
