### ISSUE TITLE
Make NightingaleTrack clickable, for example domains? 

### ISSUE THREAD

**Issue by MaxTixhon** [ebi-webcomponents/nightingale#301]
Hi,

I'm using Nightingale to represent UniProt sequences and features on a website and I have a few questions/requests.
Is there a way to make to make the tracks clickable to give basic infos such as domain names? I tried to do it on my own but I'm not a web developper so I'm struggling.

I also would like to have, as on the UniProt Feature Viewer, the pLDDT and AlphaMissense scales, is this done with the Colored Sequence track?

And lastly, I'd like to represent a custom set of variants, also like on the UniProt website but I feel that with only basic HTML/CSS/JS knowledge and the current documentation, that would be quite a challenge.

Thank you for your work, this is a really solid base to nicely implement biological data.

Max

**Comment by pesader** [comment]
Hi, @MaxTixhon! I'm trying to do the same thing. How did you manage to do it?
