### ISSUE TITLE
Demo link doesn't work.

### ISSUE THREAD

**Issue by markfortner** [ebi-webcomponents/nightingale#48]
The demo link on the word "Here" doesn't work.

**Comment by xwatkins** [comment]
Hi @markfortner thanks for reporting this, could you let me know on which page?

**Comment by kimrutherford** [comment]
This link in README.md doesn't work for me (404):

https://github.com/ebi-webcomponents/nightingale/blame/master/packages/protvista-interpro-track/README.md#L7

**Comment by xwatkins** [comment]
Thanks @kimrutherford , good to hear from you! Removed the offending link, please refer to https://ebi-webcomponents.github.io/nightingale for doc and examples.
