### ISSUE TITLE
No /dist folder for protvista-saver

### ISSUE THREAD

**Issue by 13anas** [ebi-webcomponents/nightingale#49]
Missing /dist folder for Protvista-saver package. There is only src.

**Comment by gustavo-salazar** [comment]
I just checked, the `/dist` is currently in the package: https://www.jsdelivr.com/package/npm/protvista-saver?path=dist

But beyond that this was an issue related to publishing packages without building first. we now have a `prepublish` script in `package.json` to make sure this won't happen again.
