### ISSUE TITLE
Improve datatable click behaviour

### ISSUE THREAD

**Issue by xwatkins** [ebi-webcomponents/nightingale#53]
- When a link within a row is clicked, it also triggers highlight

Steps:
- Expand a variant row in the table which has position x
- Click a position in the variation-viewer != x
- The table row will be greyed out (ie to indicate that row is not at the clicked position) while the contents of its expansion will not be greyed.
- My assumption is that the content of the expanded row also wants to be greyed out?

**Comment by gustavo-salazar** [comment]
has this been solved?
