### ISSUE TITLE
Could the showcase app automatically load examples?

### ISSUE THREAD

**Issue by xwatkins** [ebi-webcomponents/nightingale#60]
**Is your feature request related to a problem? Please describe.**
When creating a new component, you need to manually add a new `.jsx` file with route etc... to showcase it.

**Describe the solution you'd like**
it would be great to have the app iterate through the `packages` directory and load examples for each component.

**Comment by gustavo-salazar** [comment]
That would be cool.
The complications I see are about the specifics of each component, the format of the data to load, the attributes to set, etc...
Maybe defining an `/example` forlder in the package where some specification file lives and the app can use it to build the examples?
