### ISSUE TITLE
Unnecessary declaration of highlightStart and highlightEnd on ProtVistaNavigation

### ISSUE THREAD

**Issue by 13anas** [ebi-webcomponents/nightingale#63]
I've notified that the attributes `highlightStart` and `highlightEnd` are not used on the element. Also on observed attributes:
```
  static get observedAttributes() {
    return [
      "length",
      "displaystart",
      "displayend",
      "highlightStart", <--
      "highlightEnd",   <--
      "width"
    ];
  }
```

**Comment by gustavo-salazar** [comment]
Indeed they were unnecessary. It was some legacy code before we moved to `highlight` as a single attribute.
This has been updated in the `manager` and the current version doesn't include them
