### ISSUE TITLE
Can't set protvista-navigation length dynamically

### ISSUE THREAD

**Issue by 13anas** [ebi-webcomponents/nightingale#66]
I have issues setting protvista-navigation dynamically when i do it as follows:   

`document.querySelector('#protvista_navigation')['length'] = 500`

or

`document.querySelector('#protvista_navigation').setAttribute('length', 500) = 500`

**I get the following error:**

`Error: <rect> attribute x: Expected length, "NaN".`

Only can be setted this way:

`<protvista-navigation length="500" class="protvista"></protvista-navigation>`

**There's another way to do it?**

**Comment by gustavo-salazar** [comment]
Currently the `length` is only expose as an attribute, so dynamically the only way to set it up is something like
```js
document.querySelector('protvista-navigation').setAttribute('length', 500)
```
I just tested it and that seems to work. 
I'm closing the issue but feel free to reopened if there are still issues with it.

BTW, if you are using navigation inside a `protvista-manager` I would recommend to change the length in the manager and  so it propagates that into all the components.
