### ISSUE TITLE
specific range support for Navigation 

### ISSUE THREAD

**Issue by mandarsd** [ebi-webcomponents/nightingale#80]
**Is your feature request related to a problem? Please describe.**
We are creating PDBe-KB pages for processed proteins
Example : [PRO_0000449623](https://wwwdev.ebi.ac.uk/pdbe/pdbe-kb/covid19/PRO_0000449623)
As Processed proteins are actually a segment of a bigger UniPort sequence their residue numbering mostly start with some offset.  For PRO_0000449623 it starts at 3264
Currently Protvista navigation only support 1 - N range  

**Describe the solution you'd like**
It would be helpful to have an offset parameter to create navigation for a specific range

**Comment by xwatkins** [comment]
Hi @mandarsd , I think we have a similar use case for the UniProt website. 
Is what you'd like to do to display **only** the chain, or would you like to see the whole protein sequence with the view zoomed to show the chain only?

**Comment by mandarsd** [comment]
Hi @xwatkins , Yes, we just want to display the chain (specific range). Otherwise I would have set start and end attributes to zoom-in on a specific range

**Comment by gustavo-salazar** [comment]
I think this has been solved by checking the example in https://ebi-webcomponents.github.io/nightingale/#/navigation

Please feel free to reopen if that wasn't the case
