### ISSUE TITLE
Structure doesnt load

### ISSUE THREAD

**Issue by GMolini** [ebi-webcomponents/nightingale#84]
**Describe the bug**

The structure has stopped showing and just shows the LiteMol logo

**To Reproduce**
Import the package in index.html
    <script src="https://cdn.jsdelivr.net/npm/protvista-structure@latest" defer></script>

Then in a component, use the example
    <protvista-structure accession="P06493" />

**Expected behavior**
It should load the structure. When I first started using the package, it worked fined. Now it has stopped working (not sure when)

**Comment by xwatkins** [comment]
Sorry, just realised the 'molecule' field hadn't been updated in the doc (done now).
Try `<protvista-structure pdb-id="1AAP" accession="P05067" />`

**Comment by GMolini** [comment]
aaaah ok, so the problem was that I wasnt providing the pdb-id, and just the accession number. Thanks.
