### ISSUE TITLE
Infinite zoom-in

### ISSUE THREAD

**Issue by mandarsd** [ebi-webcomponents/nightingale#9]
Zoom-in should limit upto a single point. Right now it is infinite which breaks the navigation component when user tries to zoom-in beyond single residue.

**Comment by xwatkins** [comment]
I agree this should be the default behaviour. If I remember well InterPro still need infinite zoom (@4ndr01d3?) so we could have a property for this?

**Comment by gustavo-salazar** [comment]
I have set a limit when zooming in, making sure at least 2 bases are visible.
